## Perceptron From Scratch

###### ML practical 4 
###### Dhruv Patel 17162121014

In [389]:
import numpy as np

In [390]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [391]:
def sigmoid_derivative(x):
    return x*(1-x)

In [392]:
# set the hyper-parameters
lr = 0.1
epochs = 10000
inputNeurons=2
hiddenNeurons = 2
outputNeurons = 1

In [393]:
print("Hidden Layer Weights:\n{} \n\n Hidden Layer Bias: {} ".format(hidden_weights,hidden_bias))

Hidden Layer Weights:
[[5.76633265 3.46307802]
 [6.11418605 3.51654622]] 

 Hidden Layer Bias: [[-2.40002401 -5.31892491]] 


In [394]:
def train(inputs,expected_output):
    
    hidden_weights = np.random.uniform(size =(inputNeurons,hiddenNeurons))
    hidden_bias = np.random.uniform(size=(1,hiddenNeurons))

    output_weights = np.random.uniform(size =(hiddenNeurons,outputNeurons))
    output_bias = np.random.uniform(size=(1,outputNeurons))
    
    for i in range(epochs):
        #Forward Propagation
        hidden_layer_activation = np.dot(inputs,hidden_weights)+hidden_bias
        hidden_layer_output = sigmoid(hidden_layer_activation)

        output_layer_activation = np.dot(hidden_layer_output,output_weights)+output_bias
        predicted_output = sigmoid(output_layer_activation)

        #Backpropagation
        error = expected_output - predicted_output
        d_predicted_output = error * sigmoid_derivative(predicted_output)

        error_hidden_layer = d_predicted_output.dot(output_weights.T)
        d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

        #Updating Weights and Biases
        output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
        output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * lr
        hidden_weights += inputs.T.dot(d_hidden_layer) * lr
        hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr
    return predicted_output,hidden_weights,hidden_bias,output_weights,output_bias

In [395]:
def convert_binary(expected_output,preds):
    count=1
    for i in range(len(preds)):
        if preds[i][0]>=0.5:
            curr_binary =1
        else:
            curr_binary=0
        print("For input {} Expected value was: {} , Predicted Value is: {}".format(count,expected_output[i][0],curr_binary))
        count+=1

## AND Training

In [396]:
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[0],[0],[0],[1]])


In [397]:
predicted_output,hidden_weights,hidden_bias,output_weights,output_bias=train(inputs,expected_output)

In [398]:
convert_binary(expected_output,predicted_output)

For input 1 Expected value was: 0 , Predicted Value is: 0
For input 2 Expected value was: 0 , Predicted Value is: 0
For input 3 Expected value was: 0 , Predicted Value is: 0
For input 4 Expected value was: 1 , Predicted Value is: 1


In [399]:
predicted_output

array([[0.01066041],
       [0.03338145],
       [0.03328653],
       [0.95635451]])

## OR Training

In [400]:
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[0],[1],[1],[1]])


In [401]:
predicted_output,hidden_weights,hidden_bias,output_weights,output_bias=train(inputs,expected_output)

In [402]:
convert_binary(expected_output,predicted_output)

For input 1 Expected value was: 0 , Predicted Value is: 0
For input 2 Expected value was: 1 , Predicted Value is: 1
For input 3 Expected value was: 1 , Predicted Value is: 1
For input 4 Expected value was: 1 , Predicted Value is: 1


In [403]:
predicted_output

array([[0.0439979 ],
       [0.97508539],
       [0.97591499],
       [0.99387902]])

In [404]:
hidden_weights,hidden_bias,output_weights,output_bias

(array([[4.28331572, 2.27207049],
        [4.36566853, 2.08828342]]),
 array([[-2.3043133, -1.2295798]]),
 array([[6.95126293],
        [2.54207449]]),
 array([[-4.28478408]]))

## For XNOR Training

In [405]:
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[1],[0],[0],[1]])


In [406]:
predicted_output,hidden_weights,hidden_bias,output_weights,output_bias=train(inputs,expected_output)

In [407]:
convert_binary(expected_output,predicted_output)

For input 1 Expected value was: 1 , Predicted Value is: 1
For input 2 Expected value was: 0 , Predicted Value is: 0
For input 3 Expected value was: 0 , Predicted Value is: 0
For input 4 Expected value was: 1 , Predicted Value is: 1


In [408]:
predicted_output

array([[0.92290395],
       [0.08475205],
       [0.08579315],
       [0.93116725]])

In [409]:
hidden_weights,hidden_bias,output_weights,output_bias

(array([[ 5.76857211, -5.21953227],
        [-5.59050278,  5.43698515]]),
 array([[2.86923459, 2.65685291]]),
 array([[5.9384129 ],
        [5.98787295]]),
 array([[-8.73221023]]))